version: 2
jobs:
  build:
    docker:
      - image: opuscapita-docker.jfrog.io/hello-world:1
        auth:
          username: $JFROG_USER
          password: $JFROG_PASSWD
    steps:
      - run:
          name: Read MAVEN_REPO
          command: |
            echo "Hi!"
workflows:
  version: 2
  commit:
    jobs:
      - build
